[tool.poetry]
name = 'acceptence'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.13,<3.14"

[tool.poetry.dev-dependencies]
c2cwsgiutils = { extras = ["tests"], version = "6.1.7" }
psycopg2 = "2.9.10"
pytest = "8.4.1"
