# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /acceptance_tests
    schedule:
      interval: weekly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /acceptance_tests/config
    schedule:
      interval: daily
    ignore:
      - dependency-name: none

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: none
